name: monitoring-project

services:
  db-warehouse:
    image: postgres:16
    container_name: db-warehouse
    environment:
      POSTGRES_DB: db_warehouse
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-pwd
    ports:
      - "5433:5432"
    volumes:
      - ./db-warehouse-init:/docker-entrypoint-initdb.d

  db-delivery:
    image: postgres:16
    container_name: db-delivery
    environment:
      POSTGRES_DB: db_delivery
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-pwd
    ports:
      - "5432:5432"
    volumes:
      - ./db-delivery-init:/docker-entrypoint-initdb.d

  warehouse:
    image: monitoring-warehouse:0.3
    container_name: srv-warehouse
    cpus: 1.5
    mem_limit: 750m
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-warehouse:5432/db_warehouse
      SPRING_DATASOURCE_USERNAME: db-user
      SPRING_DATASOURCE_PASSWORD: db-pwd
      SPRING_DATASOURCE_HIKARI_SCHEMA: warehouse    # <-- this is actually helpful to make default schema work
    depends_on:
      - db-warehouse

  delivery:
    image: monitoring-delivery:0.3
    container_name: srv-delivery
    cpus: 1.5
    mem_limit: 750m
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-delivery:5432/db_delivery
      SPRING_DATASOURCE_USERNAME: db-user
      SPRING_DATASOURCE_PASSWORD: db-pwd
      SPRING_DATASOURCE_HIKARI_SCHEMA: delivery
    depends_on:
      - db-delivery
