name: monitoring-project

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

  db-delivery:
    image: postgres:16
    container_name: db-delivery
    environment:
      POSTGRES_DB: db_delivery
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-pwd
    ports:
      - "5432:5432"
    volumes:
      - ./db-delivery-init:/docker-entrypoint-initdb.d

  delivery:
    image: monitoring-delivery:0.2
    container_name: srv-delivery
    cpus: 1.5
    mem_limit: 750m
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-delivery:5432/db_delivery
      SPRING_DATASOURCE_USERNAME: db-user
      SPRING_DATASOURCE_PASSWORD: db-pwd
      SPRING_DATASOURCE_HIKARI_SCHEMA: delivery       # <-- this is actually helpful to make default schema work
    depends_on:
      - db-delivery
