global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'monitoring_warehouse'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['srv-warehouse:8081']

  - job_name: 'monitoring_delivery'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['srv-delivery:8080']

  - job_name: 'monitoring_warehouse_local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'monitoring_delivery_local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
