package org.burufi.monitoring.delivery.exception

enum class FailureType {
    TRANSPORT_MARK_NOT_FOUND,
    SHOPPING_CART_ID_ALREADY_EXISTS,

    // TODO IPMN-7
    ORDER_ID_NOT_FOUND,
    TRANSPORT_ID_NOT_FOUND,
    ORDER_DID_NOT_HAVE_STATUS_SENT,
    TRANSPORT_DID_NOT_HAVE_STATUS_DELIVERING,
    TRANSPORT_DID_NOT_HAVE_STATUS_RETURNING
}
