spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        # this is for H2, escaping some reserved keywords
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
